version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: pgpassword
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432